stage('Docker Login') {
    steps {
        withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials',
        usernameVariable: 'DOCKER_USER',
        passwordVariable: 'DOCKER_PASS')]) {

            bat '''
            docker login -u %DOCKER_USER% -p %DOCKER_PASS%
            '''
        }
    }
}